# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3a01bddfb246f9685636fa683648ea7c28d346d1a0653d2a07ba4ef419c84783794572b3567c558496c4822a91c1b25fbcf6d4ed00c6483e4f941779f4ef64b

test:
  secret_key_base: 2eaba811d6b7d29f6ff08192665f74947ca3138b11246338b72cbe3a3f2cb556ed45a89a611714bd2cc39adbe7e222aecbaaf19a2fe48641440efeda51ae530d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
